### ISSUE TITLE
[BUG] @2.18.0 fails to start: Cannot find module '../../../package.json'

### ISSUE THREAD

**Issue by muk-ai** [MCPJam/inspector#2870]
# Issue

First of all, thank you for building such a useful tool.

`npx @mcpjam/inspector` fails to start with `@mcpjam/inspector@2.18.0`.

Environment:

- Node.js: v26.2.0
- npm: 11.13.0
- macOS

Error:

    Error: Cannot find module '../../../package.json'
    Require stack:
    - .../node_modules/@mcpjam/inspector/dist/server/index.js

I think the issue is this line in `dist/server/index.js`:

    require("../../../package.json")

From `dist/server/index.js`, that path resolves to `node_modules/@mcpjam/package.json`, not `node_modules/@mcpjam/inspector/package.json`.

Pinning to `@mcpjam/inspector@2.17.0` works as a workaround:

    npx @mcpjam/inspector@2.17.0

**Comment by CrabAss** [comment]
I encountered this exact same issue today. I tried nodejs 20, 22 and 24 with no luck.
I tried both macOS desktop app and `npx @mcpjam/inspector@latest`, and they have the same issue.

**Comment by ignaciojimenezr** [comment]
Hey @muk-ai and @CrabAss , thanks for reporting this. This should be fixed now in `npx @mcpjam/inspector@latest`. Really sorry for the inconvenience here. Also, thanks for the kind words @muk-ai! :D

**Comment by muk-ai** [comment]
Thanks for the quick fix @ignaciojimenezr! Confirmed working on v2.18.1 🙏
